development:
  preferred_records: <%= ENV['PREFERRED_RECORDS'] || 'unc' %>
  local_institution_code: <%= ENV['LOCAL_INSTITUTION_CODE'] || 'unc' %>
  local_records: <%= ENV['LOCAL_RECORDS'] || 'unc,trln' %>
  apply_local_filter_by_default: <%= ENV['APPLY_LOCAL_FILTER_BY_DEFAULT'] || 'true' %>
  application_name: <%= ENV['APPLICATION_NAME'] || 'TRLN Argon' %>

test:
  preferred_records: <%= ENV['PREFERRED_RECORDS'] || 'unc' %>
  local_institution_code: <%= ENV['LOCAL_INSTITUTION_CODE'] || 'unc' %>
  local_records: <%= ENV['LOCAL_RECORDS'] || 'unc,trln' %>
  apply_local_filter_by_default: <%= ENV['APPLY_LOCAL_FILTER_BY_DEFAULT'] || 'true' %>
  application_name: <%= ENV['APPLICATION_NAME'] || 'TRLN Argon' %>

production:
  preferred_records: <%= ENV['PREFERRED_RECORDS'] || 'unc' %>
  local_institution_code: <%= ENV['LOCAL_INSTITUTION_CODE'] || 'unc' %>
  local_records: <%= ENV['LOCAL_RECORDS'] || 'unc,trln' %>
  apply_local_filter_by_default: <%= ENV['APPLY_LOCAL_FILTER_BY_DEFAULT'] || 'true' %>
  application_name: <%= ENV['APPLICATION_NAME'] || 'TRLN Argon' %>
