defaults: &defaults
    rollup_field: "rollup_id"
    preferred_record_field: "institution_a"
    preferred_record_value: "duke"
    local_institution: "duke"
    local_records_field: "institution_a"
    local_records_values:
      - duke
      - trln
    apply_local_filter_by_default: "true"
    application_name: "TRLN Argon"

development:
  <<: *defaults

test:
  <<: *defaults

staging:
  <<: *defaults

production:
  <<: *defaults
